version: "3.8"
services:
  jenkins:
    bouild: build/jenkins
    privileged: true
    user: root
    ports:
      - 8001:8080
    container_name: jenkins
    volumes:
      - ./data/jenkins_home:/var/jenkins_home